### PR TITLE
load cloudfront-rails in envs that use CloudFront

### PR DESCRIPTION
**Pull request by misaka**
This allows us to send the correct IPs to the analytics platform.

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased main
- [ ] Cleaned commit history
- [ ] Tested by running locally

### CODE REVIEW

**Review by defong — COMMENTED** [review]
> This gem is relevant in any deployed env in GPaaS.

What about sandboc and review apps?

**Comment by misaka** [comment]
> What about sandboc and review apps?

This is enabled for the `review`, but good point about `sandbox`. Also maybe `rollover`? And is `research` used?

**Comment by defong** [comment]
> > What about sandboc and review apps?
> 
> This is enabled for the `review`, but good point about `sandbox`. Also maybe `rollover`? And is `research` used?

Are you going to need it? Your PR descriptions imply one way and your PR changes inversely imply you don't.

**Review by defong — CHANGES_REQUESTED** [review]
I suppose it should be set for the other deployed env.

As it stands it inconclusive.

**Review by defong — APPROVED** [review]

**Pull request merged**
