### PR TITLE
Add new school placement information into the course pages

### PR DESCRIPTION
**Pull request by tomas-stefano**
## Context

Currently, the way that we communicate how school placements work is problematic for candidates. [See live site example](https://trello.com/1/cards/66df183ce08eff976808d34d/attachments/66df18f44e4f6c6d7ddd7095/download/Screenshot_2024-09-09_at_16.46.31.png).

### Requirements (Can be seem in trello but posted here too)

1. Update callout title

Update the title of the callout box from “Where you will train” to “How school placements work”

Remove the app-advice__caption “Advice from Get into Teaching”

2. Update logic - Remove existing logic

**Currently, there is logic to only display the callout boxes for some courses (we believe is it just HEI courses)**

**We want to remove this logic, and present the callout box for all courses.**

3. Add new content

We want to display different content depending on if the course is:

Provider has toggled locations on (selectable_school)
Fee-based
Salaried

4. Add to preview

When previewing the course you should be able to see the school placement guidance.

#### Provider has toggled locations on (selectable_school)
Screenshot 2024-10-17 at 05 40 49

#### Fee based

Screenshot 2024-10-17 at 05 42 52

#### Salaried based

Screenshot 2024-10-17 at 05 44 31

## Guidance to review

1. I checked the logic of the component to check edge cases and I couldn't find it, in a very very simple manner: `RecruitmentCycle.current.courses.includes(:provider).map(&:decorate).select { |course| !course.provider.selectable_school? && !course.salaried? && !course.fee? }` and the results was empty `[]`

2. Courses:

Locations Visible
[Find Version](https://find-review-4603.test.teacherservices.cloud/course/2LR/2KBG)
[Publish Version](https://publish-review-4603.test.teacherservices.cloud/publish/organisations/2LR/2025/courses/2KBG/school-placements)
- Fee:
 [Find Version](https://find-review-4603.test.teacherservices.cloud/course/1XQ/37CP)
 [Publish Version](https://publish-review-4603.test.teacherservices.cloud/publish/organisations/1XQ/2025/courses/37CP/school-placements)
- Salary:
[Find Version](https://find-review-4603.test.teacherservices.cloud/course/1CN/373T)
[Publish Version](https://publish-review-4603.test.teacherservices.cloud/publish/organisations/1CN/2025/courses/373T/school-placements)
- Apprenticeship (the content is the same as salary):
 [Find Version](https://find-review-4603.test.teacherservices.cloud/course/1CN/S909)
 [Publish Version](https://publish-review-4603.test.teacherservices.cloud/publish/organisations/1CN/2025/courses/S909/school-placements)

### CODE REVIEW

**Comment by tomas-stefano** [comment]
[Improve locations 4/6 - Update callout box logic and content](https://trello.com/c/VTg38bYy/131-improve-locations-4-6-update-callout-box-logic-and-content)

**Comment by tomas-stefano** [comment]
I made two questions on the channel #ts_fa_training_locations (waiting the answers to continue working on this PR).

**Comment by tomas-stefano** [comment]
> I made two questions on the channel #ts_fa_training_locations (waiting the answers to continue working on this PR).

All questions answered. Apprenticeships will be the same as salary funded.
Removing the restrictions on the two providers and show guidance to all.

**Comment by kelliedesigner** [comment]
### Locations visible:

- Find Version - _Looks good_
- Publish Version - Edit screen - _Looks good_
- Publish Version - Find preview - **Callout not displaying**

### Fee:

-  Find Version **Looks good**
- Publish Version - Edit screen _Looks good_
- Publish Version - Find preview **Still old content** eg https://qa.find-teacher-training-courses.service.gov.uk/course/2AT/AK12

### Salary:

- Find Version **Looks good**
- Publish Version - Edit screen _Looks good_
- Publish Version - Find preview _Looks good_

### Apprenticeship (the content is the same as salary):

-  Find Version **Looks good**
- Publish Version - Edit screen **Looks good**
- Publish Version - Find preview **Looks good**

**Comment by tomas-stefano** [comment]
Unfortunately our review apps doesn't work the "preview course". When you click preview course it redirects you to QA which gives the impression that there is a bug.

For now the only solution is to change the url to the review app...

**Review by kelliedesigner — APPROVED** [review]
LGTM

**Pull request merged**
