### PR TITLE
Accordion for non UK citizen section course page

### PR DESCRIPTION
**Pull request by CatalinVoineag**
### Context

This is part of a redesign of the course page to make it more user friendly

### Changes proposed in this pull request

Changed the entry requirements component.

| before | after |
| -- | -- |
| Screenshot from 2024-07-22 14-25-29 | Screenshot from 2024-07-22 14-25-43 |

### Guidance to review

Review code and the course show\preview page on find and publish on the review app

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally
- [ ] Inform data insights team due to database changes

### CODE REVIEW

**Comment by CatalinVoineag** [comment]
[Enhance course pages 4/5 - Restyle and update content of non-UK citizens qualification information](https://trello.com/c/0w21fJPa/1851-enhance-course-pages-4-5-restyle-and-update-content-of-non-uk-citizens-qualification-information)

**Comment by kelliedesigner** [comment]
There is a top blue border appearing when navigating on smaller viewports and only on mouse click as opposed to navigating with the keyboard.

https://github.com/user-attachments/assets/9acf5087-6494-41a0-afd2-d896747f5603

**Review by avinhurry — APPROVED** [review]
Just want to flag that the formatting looks a bit off without JS but not sure how much of an issue this is. 

Other than that looks good 🚀 

image

**Comment by kelliedesigner** [comment]
Looks good to me!

**Review by kelliedesigner — APPROVED** [review]

**Comment by CatalinVoineag** [comment]
> Just want to flag that the formatting looks a bit off without JS but not sure how much of an issue this is.
> 
> Other than that looks good 🚀
> 
> image

Good catch, I've changed it to look something like

Screenshot from 2024-07-22 16-55-49

**Pull request merged**
