### PR TITLE
[0998] Content changes on the check your answers page

### PR DESCRIPTION
**Pull request by defong**
### Context
Content changes on the check your answers page

### Changes proposed in this pull request

Removed course description
Removed course preview
Removed unneeded text
Added cancel link
Amended course name to be course title
Amended page title
Added page caption

#### Before

image

#### After
image

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally

### CODE REVIEW

**Review by avinhurry — APPROVED** [review]

**Review by simonwhatley — CHANGES_REQUESTED** [review]
The check your answers page should look like this:



- Caption: "Add course"
- Title: "Check your answers"
- The first line on the summary list should be the course title (without a change link)
- The subject level can't be changed since it impacts all other questions in the flow

**Comment by defong** [comment]
With theses bits

>     * Caption: "Add course"
> 
>     * Title: "Check your answers"
> 
>     * The first line on the summary list should be the course title (without a change link)

image

https://publish-teacher-training-pr-3328.london.cloudapps.digital/publish/organisations/1BD/2023/courses/confirmation?course%5Baccredited_body_code%5D=C55&course%5Bage_range_in_years%5D=11_to_18&course%5Bapplications_open_from%5D=2022-10-11&course%5Bcampaign_name%5D=&course%5Bcan_sponsor_skilled_worker_visa%5D=false&course%5Bfunding_type%5D=apprenticeship&course%5Bis_send%5D=1&course%5Blevel%5D=secondary&course%5Bmaster_subject_id%5D=30&course%5Bqualification%5D=pgce_with_qts&course%5Bsites_ids%5D%5B%5D=11237678&course%5Bstart_date%5D=September+2023&course%5Bstudy_mode%5D=full_time_or_part_time&course%5Bsubjects_ids%5D%5B%5D=30

**Comment by defong** [comment]
Also fixed apprentice missing value

image


https://publish-teacher-training-pr-3328.london.cloudapps.digital/publish/organisations/T92/2023/courses/confirmation?course%5Bage_range_in_years%5D=11_to_16&course%5Bapplications_open_from%5D=2022-10-11&course%5Bcampaign_name%5D=&course%5Bcan_sponsor_skilled_worker_visa%5D=false&course%5Bfunding_type%5D=apprenticeship&course%5Bis_send%5D=0&course%5Blevel%5D=secondary&course%5Bmaster_subject_id%5D=48&course%5Bqualification%5D=pgce_with_qts&course%5Bsites_ids%5D%5B%5D=11237734&course%5Bstart_date%5D=September+2023&course%5Bstudy_mode%5D=part_time&course%5Bsubjects_ids%5D%5B%5D=48

**Review by avinhurry — APPROVED** [review]

**Comment by Kateharries** [comment]
Please change 'Course title' to 'Course name'. Also 'Subject' to 'Subjects'.

**Review by simonwhatley — APPROVED** [review]

**Pull request merged**
