### PR TITLE
601 signin page for publish

### PR DESCRIPTION
**Pull request by defong**
### Context
Sign in

### Changes proposed in this pull request
Added sign in page

### Guidance to review
The whole user journey has changed.

Originally when navigating to any authenticated paths, inclusive of the root path, the user will be redirected to
- `/signin` 

Then they will be further redirected to one of the following:
- `DfE Sign In`
- `Persona`
Or 
- the `Magic` page is shown.

Now the user is redirected to `/sign-in` of which the intermittence Sign In page will be shown or the `Magic` page is shown.

####  `DfE Sign In` jounery
```yml
features:
  signin_intercept: false
  dfe_signin: true
developer_auth: false
```

####  `Persona` journey
```yml
features:
  signin_intercept: false
  dfe_signin: false
developer_auth: true
```

####  `Magic` journey
```yml
features:
  signin_intercept: true
  dfe_signin: true
  developer_auth: true
  signin_by_email: true
```

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased master
- [x] Cleaned commit history
- [x] Tested by running locally
- [ ] Product Review

### CODE REVIEW

**Comment by defong** [comment]
[Signin page for publish](https://trello.com/c/xyqQKa2L/601-signin-page-for-publish)

**Comment by gpeng** [comment]
I can't get the persona login to work anymore. Could be my set up though as the feature flags are getting confusing now. I'll pair with you and have a look together.

**Comment by gpeng** [comment]
Discussed offline.. The feature flags for this are causing no end of confusion. Let's fix those first.

**Comment by defong** [comment]
No one understands what booleans are

**Pull request closed without merging**
