### PR TITLE
Add the new values in the API document for TDA courses

### PR DESCRIPTION
**Pull request by tomas-stefano**
### Context

Publish API documentation in relation to the TDA changes.

### Changes proposed in this pull request

- Update the API documents and add the new agreed values

- Update the [ADR](https://github.com/DFE-Digital/publish-teacher-training/blob/main/guides/adr/0011-tda-courses.md) from `proposed` to `accepted`

- Move the ADR directory out of guides

### Guidance to review

Is the documentation for the TDA work sufficient? Is there anything we could add that would help someone reading this 5 years from now?

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased main
- [x] Cleaned commit history
- [x] Tested by running locally
- [x] Inform data insights team due to database changes

### CODE REVIEW

**Comment by avinhurry** [comment]
[Document Publish API TDA changes](https://trello.com/c/rXVzHeNW/1633-document-publish-api-tda-changes)

**Review by dcyoung-dev — CHANGES_REQUESTED** [review]
Do we need to include the changes to the ADR folder or can we do these separately?

**Comment by tomas-stefano** [comment]
> Do we need to include the changes to the ADR folder or can we do these separately?

Happy either way. The only goal was to change to accepted. Wdyt? Do you prefer separetely?

**Comment by tomas-stefano** [comment]
@dcyoung-dev done!

**Review by dcyoung-dev — APPROVED** [review]

**Pull request merged**
