### PR TITLE
[1839] Make course list sortable

### PR DESCRIPTION
**Pull request by avinhurry**
### Context

We are introducing new sorting capabilities for courses. You can now sort courses alphabetically (in both ascending and descending order) as well as by a predefined sequence based on `content_status` and `application_status`.

### Changes proposed in this pull request

- Change the "Course" header into a clickable link that sorts the list from a-z or z-a

- The clickable link dynamically renders a-z or z-a depending on which one it's ordered by.

- Add arrows next to the new links which represent the direction (ascending or descending)

### Guidance to review

Create courses with a wide range of status's and ensure the sorting works as expected. 

### Checklist

- [x] Make sure all information from the Trello card is in here
- [x] Attach to Trello card
- [x] Rebased main
- [ ] Cleaned commit history
- [x] Tested by running locally
- [x] Inform data insights team due to database changes

### CODE REVIEW

**Comment by avinhurry** [comment]
[Publish: The ability to sort the courses list by Name or Status](https://trello.com/c/CFDi7aW7/1839-publish-the-ability-to-sort-the-courses-list-by-name-or-status)

**Comment by inulty-dfe** [comment]
Just to confirm that this is what we want. When there are multiple tables on the page, each of them are sorted

image

**Review by dcyoung-dev — COMMENTED** [review]
My suggestionsa re mainly around readabilty of the code not so much the functionality.

I have concerns about doing sorting in Ruby and not at the database level. When I went to play around with an idea I quickly realised that moving the ordering into the database level would be very challenging 🤦‍♂️ I wondered if sorting would be kept intact if done before grouping - not sure what Rails would do 🤷

**Comment by avinhurry** [comment]
This is on hold for now, see the comments on this card: https://trello.com/c/CFDi7aW7/1839-publish-the-ability-to-sort-the-courses-list-by-name-or-status

**Comment by avinhurry** [comment]
This card has been moved into the backlog for now, see comments on: https://trello.com/c/CFDi7aW7/1839-publish-the-ability-to-sort-the-courses-list-by-name-or-status

Closing this.

**Pull request closed without merging**
