### PR TITLE
[540] Remove admin features from Publish as migrated to Support Console

### PR DESCRIPTION
**Pull request by stellenberger**
### Context

- [This trello ticket](https://trello.com/c/jr2iCZT6/540-do-clean-up-for-existing-admin-feature-on-publish-production)

### Changes proposed in this pull request

- Remove admin features on publish (except the search provider feature)

### Checklist

- [ ] Publish / TTAPI Merge - does this code change affect a part of the app that's currently being migrated to TTAPI? If so, speak with the dev doing the migration and ensure they've accounted for this change.
- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product Review

### CODE REVIEW

**Comment by stellenberger** [comment]
Blocked merging until edit SEND functionality introduced into Support Console

**Comment by stellenberger** [comment]
[Remove admin feature banner from Publish production](https://trello.com/c/CyEe5Sv8/539-remove-admin-feature-banner-from-publish-production)

**Review by defong — APPROVED** [review]
LGTM

**Review by mbocc — APPROVED** [review]
Product reviewed - banner has been removed for all personas, thank you!

**Pull request merged**
