### PR TITLE
Remove references to "_aks" environment names

### PR DESCRIPTION
**Pull request by Nitemaeric**
## Context

We've [recently dropped](https://github.com/DFE-Digital/publish-teacher-training/pull/4680) "_aks" suffixes from AKS configurations.

We should remove the "_aks" suffixes from application code too.

## Changes proposed in this pull request

- Remove previous non-aks environment configurations.
- Remove `_aks` suffix from environment names.

## Guidance to review

Let's see if `review` works :D

### CODE REVIEW

**Comment by Nitemaeric** [comment]
[Tech debt: Remove "_aks" suffixes from environment names](https://trello.com/c/ruljxvNG/249-tech-debt-remove-aks-suffixes-from-environment-names)

**Review by tomas-stefano — APPROVED** [review]
From the app point of view, looks good 👍 

Is there anything we need to do on infra side or did they already remove references to `_aks` as well? 

Such as copy/moving the settings.yml for each environment and so on?

**Comment by RMcVelia** [comment]
Could you also rename maintenance_page/manifests/env_aks to just env, or I can update on a separate pr if preferred.

**Comment by Nitemaeric** [comment]
> Could you also rename maintenance_page/manifests/env_aks to just env, or I can update on a separate pr if preferred.

Done!

I'm curious about how it knows how to pick up the changes though. The workflow file has only `production` and `qa` as options, yet the directories were named `production_aks` and `qa_aks`. Was this a bug?

**Pull request merged**
