### PR TITLE
[3364] Add sorting to training provider courses

### PR DESCRIPTION
**Pull request by gpeng**
### Context

We updated the 'Courses as an accredited body' functionality to avoid 403 errors that some users were experiencing (these were due to using the providers endpoint to retrieve the courses)

Prior to the update introduced the results were sorted by course code.

### Changes proposed in this pull request

Add sorting to the course results. The API doesn't currently support this and there is no pagination so we can just sort in the frontend.

### Checklist

- [ ] Make sure all information from the Trello card is in here
- [ ] Attach to Trello card
- [ ] Rebased master
- [ ] Cleaned commit history
- [ ] Tested by running locally
- [ ] Product Review

### CODE REVIEW

**Comment by gpeng** [comment]
[User getting 403 errors when viewing their training providers on the "courses as an accredited body" page](https://trello.com/c/OdnDymOC/3364-user-getting-403-errors-when-viewing-their-training-providers-on-the-courses-as-an-accredited-body-page)

**Comment by defong** [comment]
ummm cannot see the mirror in #1078 or tests

**Comment by fofr** [comment]
Why are they sorted by course code and not course title?

**Comment by gpeng** [comment]
That's a good question. I was almost going to change it but for this I just wanted to match what was there before as I changed the implementation and the ordering had changed. I'll merge and deploy this so it's as designed and then follow up Monica & Jesse and see was this intentional. The feature is broken at the moment so I'm keen to get this out.

**Pull request merged**
