### PR TITLE
[873] Port the new GTM container for Find into new Find

### PR DESCRIPTION
**Pull request by darokel**
### Context

https://trello.com/c/wqDjr6r7/873-port-the-new-gtm-container-for-find-into-new-find

This is a port of the work done on this PR https://github.com/DFE-Digital/find-teacher-training/pull/1437 for new Find

### Changes proposed in this pull request

Same as above but relevant for this repo.

### CODE REVIEW

**Comment by darokel** [comment]
[Port the new GTM container for Find into new Find](https://trello.com/c/wqDjr6r7/873-port-the-new-gtm-container-for-find-into-new-find)

**Review by goodviber — APPROVED** [review]
Lgtm - might be nice to have a review app just to check the CSP, I remember it caused me a bit of head scratching

**Comment by darokel** [comment]
> Lgtm - might be nice to have a review app just to check the CSP, I remember it caused me a bit of head scratching

Yeah i was going to deploy this directly to QA for testing when it came time to release. Will ping you to double check

**Comment by defong** [comment]
Long running PR that is going nowhere fast.

**Pull request closed without merging**
